id: I47F50196
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T14:28:54+00:00'
last_modified: '2022-06-10T03:58:31.174460+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14505
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8398':
      image_group_id: I1KG15201
      title: Volume 1 of gsung 'bum/_dge 'dun grub/
      total_pages: 836
      order: 1
      base_file: 8398.txt
    27F3:
      image_group_id: I1KG15202
      title: Volume 2 of gsung 'bum/_dge 'dun grub/
      total_pages: 854
      order: 2
      base_file: 27F3.txt
    0D92:
      image_group_id: I1KG15203
      title: Volume 3 of gsung 'bum/_dge 'dun grub/
      total_pages: 624
      order: 3
      base_file: 0D92.txt
    '9430':
      image_group_id: I1KG15204
      title: Volume 4 of gsung 'bum/_dge 'dun grub/
      total_pages: 544
      order: 4
      base_file: 9430.txt
    D550:
      image_group_id: I1KG15205
      title: Volume 5 of gsung 'bum/_dge 'dun grub/
      total_pages: 642
      order: 5
      base_file: D550.txt
    C6A8:
      image_group_id: I1KG15206
      title: Volume 6 of gsung 'bum/_dge 'dun grub/
      total_pages: 364
      order: 6
      base_file: C6A8.txt
    E818:
      image_group_id: I1KG15207
      title: Volume 7 of gsung 'bum/_dge 'dun grub/
      total_pages: 530
      order: 7
      base_file: E818.txt
    91E8:
      image_group_id: I1KG15208
      title: Volume 8 of gsung 'bum/_dge 'dun grub/
      total_pages: 436
      order: 8
      base_file: 91E8.txt
    F0CF:
      image_group_id: I1KG15209
      title: Volume 9 of gsung 'bum/_dge 'dun grub/
      total_pages: 690
      order: 9
      base_file: F0CF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
